# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0005_auto_20171213_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(default=1, related_name='liked_books', to='book_authors.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='book_authors.User'),
        ),
    ]
